apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - name: binarycalculator
          image: northamerica-northeast2-docker.pkg.dev/second-kiln-450617-k9/sofe3980u/binarycalculator:latest
          ports:
            - containerPort: 8080
